<Workspace Version="1.3.1.1736" X="-358.266260300416" Y="-117.388939475596" zoom="2.01045961824633" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="3e41f873-2617-4221-a7f4-04506597c4e2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="335.485138084383" y="180.063204385584" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
# Import RevitAPI Dll Assembly Classes
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager
# Create variable for Revit Document
doc = DocumentManager.Instance.CurrentDBDocument

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)


#############
# CODE HERE #
#############


# End Transaction
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="bb9178c2-a347-42c9-abfb-370d24186391" type="CoreNodeModels.Watch" nickname="Watch" x="544" y="180" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="7c0ed029-f3bd-4186-8ed8-286827ad202f" type="CoreNodeModels.Watch" nickname="Watch" x="553" y="532" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="f3d35d7e-08f7-4c5c-b841-8dbc6e7c7667" type="PythonNodeModels.PythonNode" nickname="Python Script" x="331" y="531" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
# Import RevitAPI Dll Assembly Classes
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager
# Create variable for Revit Document
doc = DocumentManager.Instance.CurrentDBDocument

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

collector = FilteredElementCollector(doc)
doors = collector.OfCategory(BuiltInCategory.OST_Doors).WhereElementIsNotElementType()

OUT = []

for door in doors:
	if door.Mirrored:
		comment_param = door.LookupParameter('Comments')
		# returns a parameter object
		comment_param.Set('Is Mirrored')
		OUT.append(door)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3e41f873-2617-4221-a7f4-04506597c4e2" start_index="0" end="bb9178c2-a347-42c9-abfb-370d24186391" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f3d35d7e-08f7-4c5c-b841-8dbc6e7c7667" start_index="0" end="7c0ed029-f3bd-4186-8ed8-286827ad202f" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="cfff010a-f68d-4d52-bd32-a4eac160d555" text="Select Mirrored Doors" x="326.726641612033" y="127.315355324184" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="cf07d0f2-b92c-42ca-9dcb-cd63091b6f0f" annotationText="Solutions" left="321" top="485" width="434" height="202" fontSize="30" InitialTop="531" InitialHeight="186" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="7c0ed029-f3bd-4186-8ed8-286827ad202f" />
      <Models ModelGuid="f3d35d7e-08f7-4c5c-b841-8dbc6e7c7667" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>